##################################################################
##### NSPanel HA  - https://github.com/otghcloud/nspanel-ha  #####
##### ESPHome Addon - Climate Control - Cool                 #####
##################################################################
---
substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
  ##############################
  ### Local thermostat defaults ###
  temp_min: ${60 if TEMP_UNIT_IS_FAHRENHEIT else 15}

esphome:
  build_flags:
    - -D NSPANEL_HA_ADDON_CLIMATE_COOL

climate:
  - id: !extend thermostat_embedded
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
    idle_action:
      - switch.turn_off: relay_${cooler_relay}
    preset:
      - name: "Off"
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"

packages:
  climate_base_package: !include nspanel_esphome_addon_climate_base.yaml
...
